LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libosip_updater
LOCAL_SRC_FILES := libosip_updater.cpp
LOCAL_C_INCLUDES += bootable/recovery external/selinux/libselinux/include

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE :=
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_TAGS := optional
OVERRIDE_BUILT_MODULE_PATH :=
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_SRC_FILES := libcgpt_static.a
LOCAL_BUILT_MODULE_STEM := libcgpt_static.a
LOCAL_STRIP_MODULE :=
LOCAL_MODULE := libcgpt_static
LOCAL_MODULE_STEM := libcgpt_static.a
LOCAL_CERTIFICATE :=
LOCAL_MODULE_PATH :=
LOCAL_REQUIRED_MODULES :=
LOCAL_WHOLE_STATIC_LIBRARIES :=
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE :=
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_TAGS := optional
OVERRIDE_BUILT_MODULE_PATH :=
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_SRC_FILES := liboempartitioning_static.a
LOCAL_BUILT_MODULE_STEM := liboempartitioning_static.a
LOCAL_STRIP_MODULE :=
LOCAL_MODULE := liboempartitioning_static
LOCAL_MODULE_STEM := liboempartitioning_static.a
LOCAL_CERTIFICATE :=
LOCAL_MODULE_PATH :=
LOCAL_REQUIRED_MODULES :=
LOCAL_WHOLE_STATIC_LIBRARIES := libcgpt_static
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE :=
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_TAGS := optional
OVERRIDE_BUILT_MODULE_PATH :=
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_SRC_FILES := libintel_updater.a
LOCAL_BUILT_MODULE_STEM := libintel_updater.a
LOCAL_STRIP_MODULE :=
LOCAL_MODULE := libintel_updater
LOCAL_MODULE_STEM := libintel_updater.a
LOCAL_CERTIFICATE :=
LOCAL_MODULE_PATH :=
LOCAL_REQUIRED_MODULES :=
LOCAL_WHOLE_STATIC_LIBRARIES := liboempartitioning_static
include $(BUILD_PREBUILT)
